host: localhost:8088
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: 自动生成api文档
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger接口文档
  version: "1.1"
paths:
  /common/tabl/weigh/:
    get:
      consumes:
      - application/json
      description: 表格拖拽排序
      parameters:
      - description: 表单ID
        in: path
        name: group_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: 接口简介
      tags:
      - 数据通用表格排序
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
